app = "fleurraine"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"

[env]
  PORT = "8080"
